# Generated by Django 4.2.4 on 2023-09-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_alter_product_id_alter_reviewrating_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sold",
            field=models.IntegerField(default=0),
        ),
    ]
