# Generated by Django 4.2.4 on 2023-09-08 22:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_product_image1_product_image2_product_image3_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image4",
        ),
    ]
