# Generated by Django 4.2.4 on 2023-09-09 00:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0006_remove_product_image4"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, max_length=1500),
        ),
    ]
